### ISSUE TITLE
Transitive dependency on log4j

### ISSUE THREAD

**Issue by e1ywka** [pnerg/akka-persistence-mock#10]
Hello! 
This project is very solid work but I suggest you to mark dependency on slf4j-log4j12 to "provided" or even "test" scope in your sbt configuration. Thanks!

**Comment by pnerg** [comment]
Well, interesting I can't actually recall why it's set as "compile" or even there...:)
Most likely just a copy/paste thing from some other project.
As it looks I'm not even using log4j in testing...should be removed completely.

Thx for notifying me.

**Comment by pnerg** [comment]
Closing the issue as it has been solved and released in [v1.1.1](https://github.com/pnerg/akka-persistence-mock/releases/tag/v1.1.1)
